version: "3"

services:
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - "80:80"
        networks:
            - devops

    jenkins:
        container_name: jenkins
        build: ../jenkins
        image: custom/jenkins
        ports:
            - "8080:8080"
            - "50000:50000"
        environment:
            - "JAVA_OPTS: -Duser.timezone=Europe/Amsterdam"
            - "JENKINS_OPTS='--prefix=/jenkins'"
        networks:
            - devops

    sonarqube:
        container_name: sonarqube
        image: sonarqube
        ports:
            - "9000:9000"
        networks:
            - devops

    nexus:
        container_name: nexus
        image: sonatype/nexus3
        ports:
            - "8081:8081"
        ulimits:
            nofile:
                soft: 98304
                hard: 98304
        networks:
            - devops

    gitlab:
        container_name: gitlab
        image: gitlab/gitlab-ce:latest
        ports:
            - "8085:80"
            - "7086:443"
            - "7087:22"
        hostname: "gitlab.example.com"
        networks:
            - devops

    tomcat_test:
        container_name: tomcat-test
        image: tomcat:9.0.10-jre8
        ports:
            - "7060:8080"
        networks:
            - devops

    tomcat_stage:
        container_name: tomcat-stage
        image: tomcat:9.0.10-jre8
        ports:
            - "7090:8080"
        networks:
            - devops

    tomcat_prod:
        container_name: tomcat-prod
        image: tomcat:9.0.10-jre8
        ports:
            - "7080:8080"
        networks:
            - devops

    influxdb:
        container_name: influxdb
        image: influxdb
        ports:
            - "8086:8086"
        environment:
            - "INFLUX_DB=influx"
            - "INFLUX_USER=admin"
            - "INFLUX_PASSWORD=admin"
        networks:
            - devops

    grafana:
        container_name: grafana
        image: grafana/grafana
        ports:
            - "3000:3000"
        environment:
            - "GF_SECURITY_ADMIN_USER=admin"
            - "GF_SECURITY_ADMIN_PASSWORD=admin"
            - "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel,grafana-piechart-panel"
        networks:
            - devops

networks:
    devops:
